name: SpringBoot CI/CD with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, my-server]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls
      - name: Deploy Artifact
        run: |
          pkill -f "java -jar $(ls)"
          nohup java -jar $(ls) > nohuo.log &

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: artifacts
