name: SpringBoot CI/CD with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, web-server]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: |
          whoami
          pwd
          mvn -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts
      - name: Deploy Artifact
        run: |
          ls
          pwd
          cd artifacts && ls
          pwd
          nohup java -jar devops-sprinboot-0.0.1-SNAPSHOT.jar > ../nohup.log &

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: artifacts