name: SpringBoot CI/CD with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: |
          whoami
          pwd
          mvn -B package --file pom.xml
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          region-id: cn-shanghai  # 3
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.REPOSITORY_URL }}:$IMAGE_TAG .
          docker tag $(docker images ${{ secrets.REPOSITORY_URL }}:$IMAGE_TAG -q) ${{ secrets.REPOSITORY_URL }}:latest
          docker push ${{ secrets.REPOSITORY_URL }}:latest
  depoly:
    needs: [ build ]
    name: Docker Pull And Run
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop $(docker ps -a | grep -w ${{ secrets.REPOSITORY_URL }}| awk '{print $1}')
            docker rm -f $(docker ps -a | grep -w ${{ secrets.REPOSITORY_URL }}| awk '{print $1}')
            docker rmi -f $(docker images  ${{ secrets.REPOSITORY_URL }}:latest -q)
            docker login --username=${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} registry.cn-shanghai.aliyuncs.com
            docker pull ${{ secrets.REPOSITORY_URL }}:latest
            docker run -d -p 8888:8888 ${{ secrets.REPOSITORY_URL }}:latest

